<?php  /* @var \WeltPixel\OwlCarouselSlider\Block\Slider\Custom $this */ ?>

<?php $sliderConfig  = $this->getSliderConfiguration(); ?>
<?php $sliderGeneral = $sliderConfig['slider_config']; ?>
<?php $enabled       = (array_key_exists('status', $sliderGeneral) && $sliderGeneral['status'] !=0) ? true : false; ?>

<?php if ($enabled) : ?>

    <?php
    $sliderId     = $this->getData('slider_id');
    $breakpoint   = $this->getBreakpointConfiguration();
    $bannerConfig = $sliderConfig['banner_config'];
    $sliderConfig = json_encode($sliderGeneral);
    $mediaUrl     = $this->getMediaUrl();
    $isGatEnabled = $this->isGatEnabled();
    ?>
    
    <?php if ($sliderGeneral['show_title'] && trim($sliderGeneral['title'])) : ?>
        <div class="content-heading">
            <h2 class="title"><?php echo $sliderGeneral['title']; ?></h2>
        </div>
    <?php endif; ?>

    
<!--  Start Slider  -->
<link rel="stylesheet" type="text/css" src="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" src_type="url">

<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_slider')->toHtml(); ?> 




		<!--  end slider -->
    <script>
        require(['jquery', 'owl_carousel', 'owl_config','slick','flexslider'],
            function ($) {
          
                $(document).ready(function() {
                
                    var slider_id = <?php echo $sliderId; ?>;
                    var slider_config = <?php echo $sliderConfig; ?>;

                    var items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 1);
                    if(slider_config.transition != 'slide') {
                        items = 1;
                    }

                    var stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0;
                    var animate_Out = slider_config.transition != 'fadeOut' ? true : false;




                    $('.slider').slick({
                          slidesToShow: 4,
                          slidesToScroll: 1,
                          autoplay: true,
                          autoplaySpeed: 5000,
                           responsive: [
                                  {
                                    breakpoint: 2921,
                                    settings: {
                                      slidesToShow: 8,
                                      slidesToScroll: 1,
                                      infinite: true
                                    }
                                  },
                                   {
                                    breakpoint: 2561,
                                    settings: {
                                      slidesToShow: 7,
                                      slidesToScroll: 1,
                                      infinite: true
                                    }
                                  },
                                  {
                                    breakpoint: 2201,
                                    settings: {
                                      slidesToShow: 6,
                                      slidesToScroll: 1,
                                      infinite: true
                                    }
                                  },
                                  {
                                    breakpoint: 1841,
                                    settings: {
                                      slidesToShow: 5,
                                      slidesToScroll: 1,
                                      infinite: true
                                    }
                                  },
                                  {
                                    breakpoint: 1481,
                                    settings: {
                                      slidesToShow: 4,
                                      slidesToScroll: 1,
                                      infinite: true
                                    }
                                  },
                                  {
                                    breakpoint: 1111,
                                    settings: {
                                      slidesToShow: 3,
                                      slidesToScroll: 1
                                    }
                                  },
                                  {
                                    breakpoint: 741,
                                    settings: {
                                      slidesToShow: 2,
                                      slidesToScroll: 1
                                    }
                                  },
                                  {
                                    breakpoint: 371,
                                    settings: {
                                      slidesToShow: 1,
                                      slidesToScroll: 1
                                    }
                                  }
                                  ]
                        });

                    $('.carousel').slick({
                          slidesToShow: 3,
                          slidesToScroll: 1,
                          autoplay: false,
                          centerMode: true,
                          variableWidth: true,
                          centerPadding: '60px',
                    });

                    $('.flexslider').flexslider({
                        animation: "slide",
                    });

                });
            });
    </script>
<?php endif; ?>
