<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = clone $block->getLoadedProductCollection();
$_productCollection = $_productCollection->clear()->addAttributeToSelect('*')->load();
$_helper = $this->helper('Magento\Catalog\Helper\Output');



$blockObj= $block->getLayout()->createBlock('Mycompany\Webservice\Block\Sidemenu');
$blockObj->setCacheable(false);
$assoc_id = $blockObj->getLoggedinUsers();

$activefeatures = $blockObj->getProductDetails($assoc_id,$sku='');


?>
    <h2><?php 

    $url = $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
    if (strpos($url, 'catalogsearch') == true) {
        echo 'Search Results';
    } else{
        echo $this->getLayer()->getCurrentCategory()->getName();
    }

    ?></h2>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php //echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <div class="row">
            <div class="col-md-10">
                <div class="row  product-row">
        <?php $iterator = 1; ?>
        <!--<ol class="products list items product-items">-->
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): 
                  
                   
               
                   $psku=strtolower($_product->getSku());
                    if($psku){
                        if (strpos($psku, 'cc_') !== false) {
                            $prodclass= 'career';
                        }else if (strpos($psku, 'ams_') !== false) {
                            $prodclass= 'ams';
                        }else{
                            $prodclass='';
                        }

                    }
                
                ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ?'<div class="col-md-3 col-sm-4 col-xs-6">' : '</div><div class="col-md-3 col-sm-4 col-xs-6">' ?>
                <!--<div class="product-item-info" data-container="product-grid">-->
                <div class="product <?php echo $prodclass?>">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="icon">
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    </div>
                    <!--<div class="product details product-item-details">-->
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <!--<strong class="product name product-item-name">-->
                        <h3>
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                            </h3>


				<?php
					$displ_cat_name = $_product->getDisplayCategory();
					$displ_url = $blockObj->getCategoryUrlByName($_product->getDisplayCategory());

                                        if($displ_url == '' || $displ_url=='#'){
                                          $displ_url = "/catalogsearch/result/?q=".$displ_cat_name;
                                        }
					
					if(isset($displ_cat_name) && $displ_cat_name!=''){
					 echo '<div class="tag"><a href="'.$displ_url.'">'.$displ_cat_name.'</a></div>';
					} else {
					 echo '<div class="tag">N/A</div>';
					}
				 ?>
                               

			    <?php
                                // $_product->getDisplayCategory()
                                //$sku=strtoupper($_product->getSku());
                               // $key= array_search($sku,$activefeatures['sku']);
                                // echo '<div class="tag"><a href="'.$activefeatures['url'][$key].'">'.$activefeatures['name'][$key].'</a></div>';//$block->getProductPriceHtml($_item, $type);
                                ?>                        
                        <!--</strong>-->
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ //echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        
                        

                    <!--</div>-->
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        <!--</ol>-->
                </div>
            </div>
        </div>
    </div>
    <?php //echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
